### ISSUE TITLE
The `schema` directive is very confusingly named

### ISSUE THREAD

**Issue by radix** [radix/sureberus#7]
Because `schema` is such an overloaded term in Cerberus, it becomes really really confusing. Here's an example schema I wrote recently:

```
type: dict
when_key_is:
  key: type
  choices:
    option-chooser:
      type: dict
      schema:
        data_service:
          type: dict
          schema:
            renderers:
              type: list
              schema:
                type: dict
                when_key_is:
                  key: flavor
                  choices:
                    default:
                      schema:
                        data: recipe
                    buttons:
                      type: dict
                      schema:
                        group_by: {type: string}
                        buttons: {type: list}
    trend: ...
    ranked-list: ...
    # and so on
```

The word "schema" refers to the following concepts in Cerberus (and thus Sureberus):

1. the thing that contains directives like `type`, `max_length`, etc.
2. the thing that specifies the schemas of dict keys and values. The word "schema" is used as a directive inside of the schema of type \# 1. The values of this dictionary also schemas of type \# 1.
3. The thing that specifies the schemas of list elements. This is in the same position as the schema of type \# 2, but it is determined at runtime whether to treat it as a dict-schema (which specifies keys and values) or a list-element schema (which is a schema of type \# 1).

If this is confusing, that's because it is.

I propose to deprecate the use of "schema" inside of these schemas and replace them as follows:

1. will be the only thing we call a "Schema", but it's really only a high-level documentation concept, not an identifier in code (other than in the function name `normalize_schema`).
2. this will be renamed to "fields", or something.
3. this will be renamed to "elements" or something.
